language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install graphicsmagick
script:
- npm run lint
- npm test --coverage
after_success: cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | codeclimate
addons:
  code_climate:
    repo_token: e530b4958df125177f497dc6e2eb11080ce4b640eba7a4856e7b4932fe2d8997
deploy:
  provider: npm
  email: sevinf@yandex-team.ru
  api_key:
    secure: YQj/i4PM/pqm/ODlEXrXpsSfkCs7FsCMk9rmpvEqKsVP0BbcV/pLe2Gw6r6yywN4TxYIJaABBEViTaoO5EjBfAh70knUSB9sMJ5jiMOvxh/UHlR7YDWT1/Eb/vKXKSzzQbnIM/6Zkqyan2UWPPo4X2AfuII3hEBzB2hMZHoGbys=
  on:
    tags: true
    repo: bem/gemini
