language: node_js
node_js:
- '0.12'
- '0.10'
- 'iojs'
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX=g++-4.8
script:
- npm run lint
- npm test --coverage
after_success: cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: sevinf@yandex-team.ru
  api_key:
    secure: YQj/i4PM/pqm/ODlEXrXpsSfkCs7FsCMk9rmpvEqKsVP0BbcV/pLe2Gw6r6yywN4TxYIJaABBEViTaoO5EjBfAh70knUSB9sMJ5jiMOvxh/UHlR7YDWT1/Eb/vKXKSzzQbnIM/6Zkqyan2UWPPo4X2AfuII3hEBzB2hMZHoGbys=
  on:
    tags: true
    all_branches: true
    repo: bem/gemini
