language: node_js
node_js:
- '0.11'
- '0.10'
script: npm test --coverage
after_success: cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | codeclimate
addons:
  code_climate:
    repo_token: e530b4958df125177f497dc6e2eb11080ce4b640eba7a4856e7b4932fe2d8997
deploy:
  provider: npm
  email: sevinf@yandex-team.ru
  api_key:
    secure: AosNa0QYNBVp81wbw+66ho+SX9PejT4m/m0vofOZC6RWKruueE0jjzb+Pb5ZnRRIZoqFcTLS55RU3zHb6XCJ+nnOgxSfzfE6GbxJHLXIBIHI+k+fzCMCJW0XJbJn9qWjd5FTuL8YaKO4qXzW52AVpr8vd0ZQKrOdJD1SFByUhEU=
  on:
    tags: true
    repo: bem/gemini
    branch: master
