language: node_js
sudo: false
script: npm run ${NPM_SCRIPT}
after_success: cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls
env:
  global:
  # SAUCE_USERNAME
  - secure: g1hP6mcOh5BRX1+4yxm6/vXYoWIHwNoIIIn0wfT8iFe8TIPwf8xAddXgU6KRAW8gUrS6hZvblpEyhz6khJ7pHsxcla5FmGg5ok8uvaD5H7o0ihmaWAOw8YYD9KgwZz6cJEk9EtsXUQmxwiDFO0Y03f97B8nxp56ENXzHQ7JGoQ4=
  # SAUCE_ACCESS_KEY
  - secure: UondfJRnFfyjIOHoC5CXMiC8kPotq4dmgI93G5KETC2yLplRMNLBGSgaa+wuow3kDk0gDamYPWl/wV0tGbKG5qAvtm8DcvgONzIamTKYElf+7wmeHSoBZQ8vbrvu2Eo+zw8kGIzreBvOnm8TxpTM1vE6mAtfXq+aBGhW3l/2Mkw=
  - CXX=g++-4.8

matrix:
  include:
    - env: NPM_SCRIPT=lint

    # unit tests
    - node_js: '4'
      env: NPM_SCRIPT='test-unit --coverage'
    - node_js: '0.10'
      env: NPM_SCRIPT='test-unit --coverage'


    - node_js: '4'
      env: NPM_SCRIPT='test-func --coverage'
    - node_js: '0.10'
      env: NPM_SCRIPT='test-func --coverage'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
